apiVersion: v1
data:
  BACKEND_ENABLED: "False"
  BACKEND_SERVICE: http://whereami-backend
  ECHO_HEADERS: "False"
  GRPC_ENABLED: "False"
  HOST: 0.0.0.0
  METADATA: backend-v2
  TRACE_SAMPLING_RATIO: "0.00"
kind: ConfigMap
metadata:
  labels:
    app: whereami-backend
    version: v2
  name: whereami-backend-v2
  namespace: backend